from django.urls import path

from .views import (
    SignInView,
    SignOutView,
    SignUpView,
    biomarker_catalog,
    guideline_dashboard,
    guideline_detail,
    guideline_workspace,
    home,
    market_workspace,
    marketing_plan_builder,
    marketing_plan_detail,
    marketing_plan_export,
    marketing_plan_gantt,
    marketing_plan_status,
    marketing_plan_workspace,
    panel_compare_result,
    panel_compare_setup,
    comparison_run_detail,
    comparison_run_export,
    comparison_run_workspace,
    final_marketing_report_builder,
    final_marketing_report_detail,
    final_marketing_report_export,
    final_marketing_report_workspace,
    panel_edit,
    panel_workspace,
    run_guideline_extraction,
    run_guideline_structuring,
    strategy_detail,
    strategy_export,
    strategy_workspace,
    therapy_panels,
    testing_panels,
)

app_name = "medstratix"

urlpatterns = [
    path("", home, name="home"),
    path("workspace/panels/", panel_workspace, name="panel_workspace"),
    path("workspace/panels/compare/", panel_compare_setup, name="panel_compare_setup"),
    path("workspace/panels/compare/result/", panel_compare_result, name="panel_compare_result"),
    path("workspace/panels/compare/runs/", comparison_run_workspace, name="comparison_run_workspace"),
    path("workspace/panels/compare/runs/<int:pk>/", comparison_run_detail, name="comparison_run_detail"),
    path("workspace/panels/compare/runs/<int:pk>/export/<str:fmt>/", comparison_run_export, name="comparison_run_export"),
    path("workspace/market/", market_workspace, name="market_workspace"),
    path("workspace/strategies/", strategy_workspace, name="strategy_workspace"),
    path("workspace/strategies/<int:pk>/", strategy_detail, name="strategy_detail"),
    path("workspace/strategies/<int:pk>/export/<str:fmt>/", strategy_export, name="strategy_export"),
    path("workspace/marketing-plans/", marketing_plan_workspace, name="marketing_plan_workspace"),
    path("workspace/final-reports/", final_marketing_report_workspace, name="final_marketing_report_workspace"),
    path("workspace/final-reports/builder/", final_marketing_report_builder, name="final_marketing_report_builder"),
    path("workspace/final-reports/<int:pk>/", final_marketing_report_detail, name="final_marketing_report_detail"),
    path("workspace/final-reports/<int:pk>/export/<str:fmt>/", final_marketing_report_export, name="final_marketing_report_export"),
    path("workspace/marketing-plans/builder/", marketing_plan_builder, name="marketing_plan_builder"),
    path("workspace/marketing-plans/<int:pk>/", marketing_plan_detail, name="marketing_plan_detail"),
    path("workspace/marketing-plans/<int:pk>/status/", marketing_plan_status, name="marketing_plan_status"),
    path("workspace/marketing-plans/<int:pk>/gantt/", marketing_plan_gantt, name="marketing_plan_gantt"),
    path("workspace/marketing-plans/<int:pk>/export/<str:fmt>/", marketing_plan_export, name="marketing_plan_export"),
    path("workspace/panels/<int:pk>/edit/", panel_edit, name="panel_edit"),
    path("workspace/dashboard/", guideline_dashboard, name="guideline_dashboard"),
    path("workspace/biomarkers/", biomarker_catalog, name="biomarker_catalog"),
    path("workspace/testing-panels/", testing_panels, name="testing_panels"),
    path("workspace/therapy-panels/", therapy_panels, name="therapy_panels"),
    path("workspace/", guideline_workspace, name="guideline_workspace"),
    path("workspace/<int:pk>/", guideline_detail, name="guideline_detail"),
    path("workspace/<int:pk>/run/", run_guideline_extraction, name="run_guideline_extraction"),
    path("workspace/<int:pk>/structure/", run_guideline_structuring, name="run_guideline_structuring"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("signin/", SignInView.as_view(), name="signin"),
    path("logout/", SignOutView.as_view(), name="logout"),
]
