# Generated by Django 5.2.13 on 2026-04-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("yours", "Your Company"),
                            ("competitor", "Competitor"),
                            ("lab", "Lab"),
                            ("guideline_body", "Guideline Body"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="TherapyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("therapy_class", models.CharField(blank=True, max_length=255)),
                ("combination_json", models.JSONField(blank=True, default=list)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("is_systemic", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuidelineDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("cancer_type", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_file",
                    models.FileField(max_length=500, upload_to="guidelines/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("imported", "Imported"),
                            ("extracted", "Extracted"),
                            ("reviewed", "Reviewed"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("published_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["cancer_type", "name", "-year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version", "year"),
                        name="unique_guideline_document_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BiomarkerDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias_json", models.JSONField(blank=True, default=list)),
                (
                    "alteration_family",
                    models.CharField(
                        choices=[
                            ("mutation", "Mutation"),
                            ("fusion", "Fusion"),
                            ("amplification", "Amplification"),
                            ("exon_skipping", "Exon Skipping"),
                            ("protein_overexpression", "Protein Overexpression"),
                            ("copy_number_gain", "Copy Number Gain"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_actionable", models.BooleanField(default=False)),
                ("priority_rank", models.PositiveIntegerField(default=0)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biomarker_definitions",
                        to="medstratix.gene",
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarker_definitions",
                        to="medstratix.guidelinedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["guideline_document", "priority_rank", "gene__symbol"],
            },
        ),
        migrations.CreateModel(
            name="GuidelineSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_code", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_text", models.TextField()),
                ("normalized_text", models.TextField(blank=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("biomarker", "Biomarker"),
                            ("therapy", "Therapy"),
                            ("testing", "Testing"),
                            ("discussion", "Discussion"),
                            ("algorithm", "Algorithm"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="medstratix.guidelinedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["guideline_document", "page_start", "title"],
            },
        ),
        migrations.CreateModel(
            name="BiomarkerVariantRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variant_label", models.CharField(max_length=255)),
                ("variant_type", models.CharField(blank=True, max_length=100)),
                ("variant_details_json", models.JSONField(blank=True, default=dict)),
                ("testing_context", models.TextField(blank=True)),
                ("histology_context", models.CharField(blank=True, max_length=255)),
                ("stage_context", models.CharField(blank=True, max_length=255)),
                ("disease_setting", models.CharField(blank=True, max_length=255)),
                ("line_of_therapy", models.CharField(blank=True, max_length=100)),
                ("is_preferred", models.BooleanField(default=False)),
                ("evidence_level", models.CharField(blank=True, max_length=100)),
                (
                    "recommendation_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "biomarker_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_rules",
                        to="medstratix.biomarkerdefinition",
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarker_variant_rules",
                        to="medstratix.guidelinedocument",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_rules",
                        to="medstratix.guidelinesection",
                    ),
                ),
            ],
            options={
                "ordering": ["biomarker_definition__gene__symbol", "variant_label"],
            },
        ),
        migrations.CreateModel(
            name="MolecularProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancer_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("clinical_context", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecular_profiles",
                        to="medstratix.guidelinedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["guideline_document", "name"],
            },
        ),
        migrations.AddField(
            model_name="biomarkerdefinition",
            name="molecular_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biomarker_definitions",
                to="medstratix.molecularprofile",
            ),
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tat",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="turnaround time"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panels",
                        to="medstratix.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overlap_count", models.PositiveIntegerField(default=0)),
                ("unique_a_count", models.PositiveIntegerField(default=0)),
                ("unique_b_count", models.PositiveIntegerField(default=0)),
                (
                    "coverage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("report_json", models.JSONField(blank=True, default=dict)),
                (
                    "panel_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_reports_as_a",
                        to="medstratix.panel",
                    ),
                ),
                (
                    "panel_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_reports_as_b",
                        to="medstratix.panel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PanelGene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_genes",
                        to="medstratix.gene",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_genes",
                        to="medstratix.panel",
                    ),
                ),
            ],
            options={
                "ordering": ["panel__name", "gene__symbol"],
            },
        ),
        migrations.AddField(
            model_name="panel",
            name="genes",
            field=models.ManyToManyField(
                related_name="panels",
                through="medstratix.PanelGene",
                to="medstratix.gene",
            ),
        ),
        migrations.CreateModel(
            name="PanelGuidelineMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancer_type", models.CharField(max_length=255)),
                ("match_status", models.CharField(blank=True, max_length=100)),
                ("matched_genes_count", models.PositiveIntegerField(default=0)),
                (
                    "missing_actionable_genes_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "coverage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_matches",
                        to="medstratix.guidelinedocument",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guideline_matches",
                        to="medstratix.panel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PanelGuidelineGeneMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("present_actionable", "Present Actionable"),
                            ("present_non_actionable", "Present Non-Actionable"),
                            ("missing_actionable", "Missing Actionable"),
                            (
                                "present_but_incomplete_for_variant_detection",
                                "Present But Incomplete",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("testing_relevance", models.TextField(blank=True)),
                ("therapy_relevance", models.TextField(blank=True)),
                ("notes_json", models.JSONField(blank=True, default=dict)),
                (
                    "biomarker_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="panel_gene_matches",
                        to="medstratix.biomarkerdefinition",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guideline_gene_matches",
                        to="medstratix.gene",
                    ),
                ),
                (
                    "panel_guideline_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_matches",
                        to="medstratix.panelguidelinematch",
                    ),
                ),
            ],
            options={
                "ordering": ["gene__symbol"],
            },
        ),
        migrations.CreateModel(
            name="StrategyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_json", models.JSONField(blank=True, default=dict)),
                (
                    "competitor_panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_reports_as_competitor",
                        to="medstratix.panel",
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="strategy_reports",
                        to="medstratix.guidelinedocument",
                    ),
                ),
                (
                    "your_panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_reports_as_yours",
                        to="medstratix.panel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestingMethodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("dna_ngs", "DNA NGS"),
                            ("rna_ngs", "RNA NGS"),
                            ("tissue_testing", "Tissue Testing"),
                            ("plasma_testing", "Plasma Testing"),
                            ("ihc", "IHC"),
                            ("fish", "FISH"),
                            ("rt_pcr", "RT-PCR"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("preferred_rank", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "biomarker_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testing_method_rules",
                        to="medstratix.biomarkerdefinition",
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testing_method_rules",
                        to="medstratix.guidelinedocument",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_method_rules",
                        to="medstratix.guidelinesection",
                    ),
                ),
            ],
            options={
                "ordering": ["biomarker_definition__gene__symbol", "preferred_rank"],
            },
        ),
        migrations.CreateModel(
            name="GuidelineTherapyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("therapy_line", models.CharField(blank=True, max_length=100)),
                (
                    "therapy_role",
                    models.CharField(
                        choices=[
                            ("first_line", "First Line"),
                            ("subsequent", "Subsequent"),
                            ("maintenance", "Maintenance"),
                            ("preferred", "Preferred"),
                            (
                                "useful_in_certain_circumstances",
                                "Useful in Certain Circumstances",
                            ),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("patient_context", models.TextField(blank=True)),
                ("histology_context", models.CharField(blank=True, max_length=255)),
                ("stage_context", models.CharField(blank=True, max_length=255)),
                (
                    "recommendation_strength",
                    models.CharField(blank=True, max_length=100),
                ),
                ("evidence_level", models.CharField(blank=True, max_length=100)),
                ("special_notes", models.TextField(blank=True)),
                (
                    "biomarker_variant_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_rules",
                        to="medstratix.biomarkervariantrule",
                    ),
                ),
                (
                    "guideline_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_rules",
                        to="medstratix.guidelinedocument",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="therapy_rules",
                        to="medstratix.guidelinesection",
                    ),
                ),
                (
                    "molecular_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_rules",
                        to="medstratix.molecularprofile",
                    ),
                ),
                (
                    "therapy_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guideline_rules",
                        to="medstratix.therapydefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["therapy_definition__name"],
            },
        ),
        migrations.AddIndex(
            model_name="guidelinesection",
            index=models.Index(
                fields=["guideline_document", "section_code"],
                name="medstratix__guideli_e8dd69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biomarkervariantrule",
            index=models.Index(
                fields=["stage_context", "line_of_therapy"],
                name="medstratix__stage_c_07538d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="molecularprofile",
            constraint=models.UniqueConstraint(
                fields=("guideline_document", "name"),
                name="unique_molecular_profile_per_guideline",
            ),
        ),
        migrations.AddConstraint(
            model_name="biomarkerdefinition",
            constraint=models.UniqueConstraint(
                fields=(
                    "guideline_document",
                    "molecular_profile",
                    "gene",
                    "alteration_family",
                ),
                name="unique_biomarker_definition_per_guideline_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="panelgene",
            constraint=models.UniqueConstraint(
                fields=("panel", "gene"), name="unique_gene_per_panel"
            ),
        ),
        migrations.AddConstraint(
            model_name="panel",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_panel_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="panelguidelinematch",
            constraint=models.UniqueConstraint(
                fields=("panel", "guideline_document"),
                name="unique_panel_guideline_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="panelguidelinegenematch",
            constraint=models.UniqueConstraint(
                fields=("panel_guideline_match", "gene", "match_type"),
                name="unique_panel_guideline_gene_match",
            ),
        ),
        migrations.AddIndex(
            model_name="guidelinetherapyrule",
            index=models.Index(
                fields=["biomarker_variant_rule", "therapy_line"],
                name="medstratix__biomark_d697fb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="guidelinetherapyrule",
            constraint=models.UniqueConstraint(
                fields=(
                    "guideline_document",
                    "biomarker_variant_rule",
                    "therapy_definition",
                    "therapy_line",
                    "source_section",
                ),
                name="unique_guideline_therapy_rule",
            ),
        ),
    ]
