# Generated by Django 5.2.13 on 2026-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomarkerdefinition",
            name="cancer_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="biomarkerdefinition",
            name="guideline_context",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="biomarkervariantrule",
            name="cancer_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="biomarkervariantrule",
            name="guideline_context",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="guidelinetherapyrule",
            name="cancer_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="guidelinetherapyrule",
            name="guideline_context",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="testingmethodrule",
            name="cancer_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="testingmethodrule",
            name="guideline_context",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
