# Generated by Django 5.2.13 on 2026-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0002_biomarkerdefinition_cancer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("tissue", "Tissue"),
                    ("plasma", "Plasma"),
                    ("other", "Other"),
                ],
                default="tissue",
                max_length=32,
            ),
        ),
    ]
