# Generated by Django 5.2.13 on 2026-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0003_panel_sample_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="supports_cnv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_dna_ngs",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_fusions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_ihc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_msi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_rna_ngs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="supports_tmb",
            field=models.BooleanField(default=False),
        ),
    ]
