# Generated by Django 5.2.13 on 2026-04-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0004_panel_supports_cnv_panel_supports_dna_ngs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyreport",
            name="campaigns_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="disease_focus",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="executive_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="guideline_advantages_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="llm_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="llm_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="market_gap_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="sales_pitch_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="status",
            field=models.CharField(default="draft", max_length=64),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="swot_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="LLMGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "operation",
                    models.CharField(default="strategy_generation", max_length=100),
                ),
                ("status", models.CharField(default="completed", max_length=64)),
                ("prompt_text", models.TextField(blank=True)),
                ("response_text", models.TextField(blank=True)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("response_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "strategy_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_logs",
                        to="medstratix.strategyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
