# Generated by Django 5.2.13 on 2026-04-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0005_strategyreport_campaigns_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("diagnostic_center", "Diagnostic Center"),
                            ("clinic", "Clinic"),
                            ("chamber", "Physician Chamber"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                (
                    "decision_style",
                    models.CharField(
                        choices=[
                            ("institution", "Institution Driven"),
                            ("doctor", "Doctor Driven"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=32,
                    ),
                ),
                ("disease_focus", models.CharField(blank=True, max_length=255)),
                ("estimated_test_volume", models.CharField(blank=True, max_length=255)),
                (
                    "evidence_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "price_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "tat_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("conference_interest", models.BooleanField(default=False)),
                ("education_interest", models.BooleanField(default=False)),
                (
                    "market_corruption_pressure",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "referral_distortion_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("compliance_red_flags", models.TextField(blank=True)),
                ("ethical_growth_goal", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="strategyreport",
            name="market_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategy_reports",
                to="medstratix.marketaccount",
            ),
        ),
        migrations.CreateModel(
            name="MarketStakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("pathologist", "Pathologist"),
                            ("oncologist", "Oncologist"),
                            ("procurement", "Procurement"),
                            ("admin", "Administrator"),
                            ("lab_manager", "Lab Manager"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=255)),
                (
                    "influence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "evidence_preference",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("conference_interest", models.BooleanField(default=False)),
                ("service_expectation", models.TextField(blank=True)),
                ("behavioral_notes", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="medstratix.marketaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["account__name", "name"],
            },
        ),
    ]
