# Generated by Django 5.2.13 on 2026-04-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0006_marketaccount_strategyreport_market_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("disease_filter", models.CharField(blank=True, max_length=255)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                (
                    "competitor_panels",
                    models.ManyToManyField(
                        related_name="comparison_runs_as_competitors",
                        to="medstratix.panel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comparison_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "your_panels",
                    models.ManyToManyField(
                        related_name="comparison_runs_as_yours", to="medstratix.panel"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
