# Generated by Django 5.2.13 on 2026-04-21 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0007_comparisonrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmgenerationlog",
            name="strategy_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_logs",
                to="medstratix.strategyreport",
            ),
        ),
        migrations.CreateModel(
            name="MarketingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("objective", models.TextField(blank=True)),
                ("geography", models.CharField(blank=True, max_length=255)),
                ("disease_focus", models.CharField(blank=True, max_length=255)),
                ("output_style", models.CharField(default="brief_plan", max_length=64)),
                ("include_product_context", models.BooleanField(default=False)),
                ("strategist_note", models.TextField(blank=True)),
                ("status", models.CharField(default="draft", max_length=64)),
                ("executive_summary", models.TextField(blank=True)),
                ("llm_provider", models.CharField(blank=True, max_length=100)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                ("plan_json", models.JSONField(blank=True, default=dict)),
                ("plan_text", models.TextField(blank=True)),
                ("report_json", models.JSONField(blank=True, default=dict)),
                (
                    "comparison_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_plans",
                        to="medstratix.comparisonrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_plans",
                        to="medstratix.marketaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="llmgenerationlog",
            name="marketing_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_logs",
                to="medstratix.marketingplan",
            ),
        ),
    ]
