# Generated by Django 5.2.13 on 2026-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "medstratix",
            "0008_alter_llmgenerationlog_strategy_report_marketingplan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="marketstakeholder",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
