# Generated by Django 5.2.13 on 2026-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medstratix", "0009_marketstakeholder_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="gene_panel_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="panel",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
